*Final Dataset for Dissertation. Last Update 8.30.19


//If not using my personal computer use below
import excel "https://docs.google.com/uc?id=1xILLWJ5fy_8VxENiQK2yscbGBUFBlsY8&export=download", firstrow clear
//

import excel "/Users/yosmerizroman/Downloads/Dissertation Dataset 8.19.19.xlsx", sheet("Dissertation Dataset 8.19.19") firstrow clear
//VARIABLE GENERATING--DATA CLEANUP
gen EOF_LIT=EOF_CODES
replace EOF_LIT= "Confirmed" if EOF_LIT== "C"
replace EOF_LIT= "FA INELIGIBLE, EOF AD" if EOF_LIT== "$"
replace EOF_LIT= "NotEOF Precollege required" if EOF_LIT== "G"
replace EOF_LIT= "FA INELIGIBLE" if EOF_LIT== "N"
replace EOF_LIT= "Potential" if EOF_LIT== "P"
replace EOF_LIT= "Eligible FA required" if EOF_LIT== "R"
replace EOF_LIT= "10 percent override" if EOF_LIT== "T"
replace EOF_LIT= "FAQ No Decision" if EOF_LIT== "U"
replace EOF_LIT= "Non Compliance" if EOF_LIT== "V"
replace EOF_LIT= "ACADEMICALLY INELIGIBLE" if EOF_LIT== "W"
gen EOF_IND=EOF_LIT
replace EOF_IND="1" if EOF_IND=="Confirmed"
replace EOF_IND="0" if EOF_LIT=="FA INELIGIBLE, EOF AD"
replace EOF_IND="0" if EOF_LIT=="NotEOF Precollege required"
replace EOF_IND="0" if EOF_LIT=="FA INELIGIBLE"
replace EOF_IND="0" if EOF_LIT=="Potential"
replace EOF_IND="0" if EOF_LIT=="Eligible FA required"
replace EOF_IND="0" if EOF_LIT=="10 percent override"
replace EOF_IND="0" if EOF_LIT=="FAQ No Decision"
replace EOF_IND="0" if EOF_LIT=="Non Compliance"
replace EOF_IND="0" if EOF_LIT=="ACADEMICALLY INELIGIBLE"
replace EOF_IND="3" if EOF_LIT==""
gen EOF_INDICATOR=EOF_IND
replace EOF_IND="2" if EOF_IND=="3"
replace EOF_INDICATOR="NON-EOF" if EOF_IND=="0"
replace EOF_INDICATOR="NON-EOF" if EOF_IND=="2"
replace EOF_INDICATOR="EOF" if EOF_IND=="1"
tab EOF_INDICATOR
tab EOF_INDICATOR GENDER
tab EOF_INDICATOR REGION_CD
tab EOF_INDICATOR HIGH_DITRESS_MNCPLTY
replace DFG_SCHOOL="1" if DFG_SCHOOL=="D"
replace DFG_SCHOOL="0" if DFG_SCHOOL==""
tab DFG_SCHOOL
tab EOF_INDICATOR DFG_SCHOOL
gen FATHER_COLLEGE=FATHER_EDU
replace FATHER_COLLEGE="0" if FATHER_COLLEGE=="0"
replace FATHER_COLLEGE="0" if FATHER_COLLEGE=="1"
replace FATHER_COLLEGE="0" if FATHER_COLLEGE=="2"
replace FATHER_COLLEGE="1" if FATHER_COLLEGE=="3"
replace FATHER_COLLEGE="1" if FATHER_COLLEGE=="4"
gen MOTHER_COLLEGE=MOTHER_EDU
replace MOTHER_COLLEGE="0" if MOTHER_COLLEGE=="0"
replace MOTHER_COLLEGE="0" if MOTHER_COLLEGE=="1"
replace MOTHER_COLLEGE="0" if MOTHER_COLLEGE=="2"
replace MOTHER_COLLEGE="1" if MOTHER_COLLEGE=="3"
replace MOTHER_COLLEGE="1" if MOTHER_COLLEGE=="4"
gen FATHER_COLLEGE_LIT=FATHER_COLLEGE
replace FATHER_COLLEGE_LIT="ATTENDED" if FATHER_COLLEGE_LIT=="1"
replace FATHER_COLLEGE_LIT="NOT_ATTENDED" if FATHER_COLLEGE_LIT=="0"
gen MOTHER_COLLEGE_LIT=MOTHER_COLLEGE
replace MOTHER_COLLEGE_LIT="ATTENDED" if MOTHER_COLLEGE_LIT=="1"
replace MOTHER_COLLEGE_LIT="NOT_ATTENDED" if MOTHER_COLLEGE_LIT=="0"
//CATEGORICAL VARIABLES 
tab FATHER_COLLEGE
tab FATHER_COLLEGE_LIT
tab FATHER_EDU
tab MOTHER_COLLEGE
tab MOTHER_COLLEGE_LIT
tab MOTHER_EDU
tab EOF_INDICATOR FATHER_COLLEGE
tab EOF_INDICATOR MOTHER_COLLEGE
replace NAT_SCH_LUNCH="N" if NAT_SCH_LUNCH==""
tab EOF_INDICATOR EOF_SIBLING
replace EOF_SIBLING="Y" if EOF_SIBLING=="C"
tab EOF_INDICATOR EOF_SIBLING
tab EOF_INDICATOR NAT_SCH_LUNCH 
tab EOF_INDICATOR COLL_PREP_PROG
tab UNIT EOF_INDICATOR
replace WARD_OF_COURT="BLANK" if WARD_OF_COURT==""
//CONTINUOUS VARIABLES
misstable summarize
su HOUSEHOLDAGI if HOUSEHOLDAGI !=.
su HOUSEHOLDAGI if EOF_INDICATOR=="EOF"
su HOUSEHOLDAGI if EOF_INDICATOR=="NON-EOF"
su EFC if EFC !=.
su EFC if EOF_INDICATOR=="EOF"
su EFC if EOF_INDICATOR=="NON-EOF"
su SATSCORE if SATSCORE !=.
su SATSCORE if EOF_INDICATOR=="EOF"
su SATSCORE if EOF_INDICATOR=="NON-EOF"
su HS_GPA if HS_GPA !=.
su HS_GPA if EOF_INDICATOR=="EOF"
su HS_GPA if EOF_INDICATOR=="NON-EOF"
su HS_PCTILE_RANK if HS_PCTILE_RANK !=.
su HS_PCTILE_RANK if EOF_INDICATOR=="EOF"
su HS_PCTILE_RANK if EOF_INDICATOR=="NON-EOF"
su ACT_COMP if ACT_COMP !=.
su ACT_COMP if EOF_INDICATOR=="EOF"
su ACT_COMP if EOF_INDICATOR=="NON-EOF"
su AGE_AT_START if AGE_AT_START !=.
su AGE_AT_START if EOF_INDICATOR=="EOF"
su AGE_AT_START if EOF_INDICATOR=="NON-EOF"
su T1_GPA_TERM if T1_GPA_TERM !=.
su T1_GPA_TERM if EOF_INDICATOR=="EOF"
su T1_GPA_TERM if EOF_INDICATOR=="NON-EOF"
su SP1_GPA_TERM if SP1_GPA_TERM !=.
su SP1_GPA_TERM if EOF_INDICATOR=="EOF"
su SP1_GPA_TERM if EOF_INDICATOR=="NON-EOF"
su SP1_GPA_CUM if SP1_GPA_CUM !=.
su SP1_GPA_CUM if EOF_INDICATOR=="EOF"
su SP1_GPA_CUM if EOF_INDICATOR=="NON-EOF"
su T2_GPA_TERM if T2_GPA_TERM !=.
su T2_GPA_TERM if EOF_INDICATOR=="EOF"
su T2_GPA_TERM if EOF_INDICATOR=="NON-EOF"
su T2_GPA_CUM if T2_GPA_CUM !=.
su T2_GPA_CUM if EOF_INDICATOR=="EOF"
su T2_GPA_CUM if EOF_INDICATOR=="NON-EOF"
//DEPENDENT VARIABLES-RETENTION
tab SEC_FALL_RET if EOF_INDICATOR=="EOF"
tab SEC_FALL_RET if EOF_INDICATOR=="NON-EOF"
tab THRD_FALL_RET if EOF_INDICATOR=="EOF"
tab THRD_FALL_RET if EOF_INDICATOR=="NON-EOF"
//CROSSSTABULATIONS FY TO SO
tab GENDER SEC_FALL_RET, col row
tab GENDER SEC_FALL_RET if EOF_INDICATOR=="EOF", col row
tab GENDER SEC_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab UNIT SEC_FALL_RET, col row
tab UNIT SEC_FALL_RET if EOF_INDICATOR=="EOF", col row
tab UNIT SEC_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab REGION_CD SEC_FALL_RET, col row
tab REGION_CD SEC_FALL_RET if EOF_INDICATOR=="EOF", col row
tab REGION_CD SEC_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab DFG_SCHOOL SEC_FALL_RET, col row
tab DFG_SCHOOL SEC_FALL_RET if EOF_INDICATOR=="EOF", col row
tab DFG_SCHOOL SEC_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
/* POCKET OF POVERTY SAME AS HIGH DISTRESS MUNICIPALITY IN HOW ITS CODED*/
replace HIGH_DITRESS_MNCPLTY="HIGH DISTRESS MUNICIPALITY" if HIGH_DITRESS_MNCPLTY=="POCKET OF POVERTY"
tab HIGH_DITRESS_MNCPLTY
tab HIGH_DITRESS_MNCPLTY SEC_FALL_RET, col row
tab HIGH_DITRESS_MNCPLTY SEC_FALL_RET if EOF_INDICATOR=="EOF", col row
tab HIGH_DITRESS_MNCPLTY SEC_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab FATHER_COLLEGE SEC_FALL_RET, col row
tab FATHER_COLLEGE SEC_FALL_RET if EOF_INDICATOR=="EOF", col row
tab FATHER_COLLEGE SEC_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab MOTHER_COLLEGE SEC_FALL_RET, col row
tab MOTHER_COLLEGE SEC_FALL_RET if EOF_INDICATOR=="EOF", col row
tab MOTHER_COLLEGE SEC_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
//generating variable for parent combinations
gen FATHER_MOTHER_ATTEND=MOTHER_COLLEGE /*BOTH PARENTS ATTENDED*/
replace FATHER_MOTHER_ATTEND="1" if FATHER_COLLEGE=="1" & MOTHER_COLLEGE=="1"
replace FATHER_MOTHER_ATTEND="0" if FATHER_COLLEGE=="0" & MOTHER_COLLEGE=="0"
replace FATHER_MOTHER_ATTEND="0" if FATHER_COLLEGE=="1" & MOTHER_COLLEGE=="0"
replace FATHER_MOTHER_ATTEND="0" if FATHER_COLLEGE=="0" & MOTHER_COLLEGE=="1"
tab FATHER_MOTHER_ATTEND
gen FATHER_MOTHER_NOT_ATTEND=FATHER_MOTHER_ATTEND /*NEITHER PARENTS ATTENDED*/
replace FATHER_MOTHER_NOT_ATTEND="1" if FATHER_COLLEGE=="0" & MOTHER_COLLEGE=="0"
replace FATHER_MOTHER_NOT_ATTEND="0" if FATHER_COLLEGE=="1" & MOTHER_COLLEGE=="1"
replace FATHER_MOTHER_NOT_ATTEND="0" if FATHER_COLLEGE=="1" & MOTHER_COLLEGE=="0"
replace FATHER_MOTHER_NOT_ATTEND="0" if FATHER_COLLEGE=="0" & MOTHER_COLLEGE=="1"
tab FATHER_MOTHER_NOT_ATTEND
gen FATHER_Y_NO_MOM=FATHER_MOTHER_ATTEND /*FATHER ATTENDED NOT MOTHER*/
replace FATHER_Y_NO_MOM="1" if FATHER_COLLEGE=="1" & MOTHER_COLLEGE=="0"
replace FATHER_Y_NO_MOM="0" if FATHER_COLLEGE=="1" & MOTHER_COLLEGE=="1"
replace FATHER_Y_NO_MOM="0" if FATHER_COLLEGE=="0" & MOTHER_COLLEGE=="0"
replace FATHER_Y_NO_MOM="0" if FATHER_COLLEGE=="0" & MOTHER_COLLEGE=="1"
tab FATHER_Y_NO_MOM
gen MOTHER_Y_NO_FAT=FATHER_Y_NO_MOM /*MOTHER ATTENDED NOT FATHER*/
replace MOTHER_Y_NO_FAT="1" if FATHER_COLLEGE=="0" & MOTHER_COLLEGE=="1"
replace MOTHER_Y_NO_FAT="0" if FATHER_COLLEGE=="1" & MOTHER_COLLEGE=="1"
replace MOTHER_Y_NO_FAT="0" if FATHER_COLLEGE=="0" & MOTHER_COLLEGE=="0"
replace MOTHER_Y_NO_FAT="0" if FATHER_COLLEGE=="1" & MOTHER_COLLEGE=="0"
tab MOTHER_Y_NO_FAT
//
tab FATHER_MOTHER_ATTEND SEC_FALL_RET, col row
tab FATHER_MOTHER_ATTEND SEC_FALL_RET if EOF_INDICATOR=="EOF", col row
tab FATHER_MOTHER_ATTEND SEC_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab FATHER_MOTHER_NOT_ATTEND SEC_FALL_RET, col row
tab FATHER_MOTHER_NOT_ATTEND SEC_FALL_RET if EOF_INDICATOR=="EOF", col row
tab FATHER_MOTHER_NOT_ATTEND SEC_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab FATHER_Y_NO_MOM SEC_FALL_RET, col row
tab FATHER_Y_NO_MOM SEC_FALL_RET if EOF_INDICATOR=="EOF", col row
tab FATHER_Y_NO_MOM SEC_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab MOTHER_Y_NO_FAT SEC_FALL_RET, col row
tab MOTHER_Y_NO_FAT SEC_FALL_RET if EOF_INDICATOR=="EOF", col row
tab MOTHER_Y_NO_FAT SEC_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab EOF_SIBLING SEC_FALL_RET, col row
tab EOF_SIBLING SEC_FALL_RET if EOF_INDICATOR=="EOF", col row
tab EOF_SIBLING SEC_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab NAT_SCH_LUNCH SEC_FALL_RET, col row
tab NAT_SCH_LUNCH SEC_FALL_RET if EOF_INDICATOR=="EOF", col row
tab NAT_SCH_LUNCH SEC_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab COLL_PREP_PROG SEC_FALL_RET, col row
tab COLL_PREP_PROG SEC_FALL_RET if EOF_INDICATOR=="EOF", col row
tab COLL_PREP_PROG SEC_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
//CROSSSTABULATIONS SO TO JR
tab GENDER THRD_FALL_RET, col row
tab GENDER THRD_FALL_RET if EOF_INDICATOR=="EOF", col row
tab GENDER THRD_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab UNIT THRD_FALL_RET, col row
tab UNIT THRD_FALL_RET if EOF_INDICATOR=="EOF", col row
tab UNIT THRD_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab REGION_CD THRD_FALL_RET, col row
tab REGION_CD THRD_FALL_RET if EOF_INDICATOR=="EOF", col row
tab REGION_CD THRD_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab DFG_SCHOOL THRD_FALL_RET, col row
tab DFG_SCHOOL THRD_FALL_RET if EOF_INDICATOR=="EOF", col row
tab DFG_SCHOOL THRD_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab HIGH_DITRESS_MNCPLTY THRD_FALL_RET, col row
tab HIGH_DITRESS_MNCPLTY THRD_FALL_RET if EOF_INDICATOR=="EOF", col row
tab HIGH_DITRESS_MNCPLTY THRD_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab FATHER_COLLEGE THRD_FALL_RET, col row
tab FATHER_COLLEGE THRD_FALL_RET if EOF_INDICATOR=="EOF", col row
tab FATHER_COLLEGE THRD_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab MOTHER_COLLEGE THRD_FALL_RET, col row
tab MOTHER_COLLEGE THRD_FALL_RET if EOF_INDICATOR=="EOF", col row
tab MOTHER_COLLEGE THRD_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab EOF_SIBLING THRD_FALL_RET, col row
tab EOF_SIBLING THRD_FALL_RET if EOF_INDICATOR=="EOF", col row
tab EOF_SIBLING THRD_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab NAT_SCH_LUNCH THRD_FALL_RET, col row
tab NAT_SCH_LUNCH THRD_FALL_RET if EOF_INDICATOR=="EOF", col row
tab NAT_SCH_LUNCH THRD_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab COLL_PREP_PROG THRD_FALL_RET, col row
tab COLL_PREP_PROG THRD_FALL_RET if EOF_INDICATOR=="EOF", col row
tab COLL_PREP_PROG THRD_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
//
tab FATHER_MOTHER_ATTEND THRD_FALL_RET, col row
tab FATHER_MOTHER_ATTEND THRD_FALL_RET if EOF_INDICATOR=="EOF", col row
tab FATHER_MOTHER_ATTEND THRD_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab FATHER_MOTHER_NOT_ATTEND THRD_FALL_RET, col row
tab FATHER_MOTHER_NOT_ATTEND THRD_FALL_RET if EOF_INDICATOR=="EOF", col row
tab FATHER_MOTHER_NOT_ATTEND THRD_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab FATHER_Y_NO_MOM THRD_FALL_RET, col row
tab FATHER_Y_NO_MOM THRD_FALL_RET if EOF_INDICATOR=="EOF", col row
tab FATHER_Y_NO_MOM THRD_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab MOTHER_Y_NO_FAT THRD_FALL_RET, col row
tab MOTHER_Y_NO_FAT THRD_FALL_RET if EOF_INDICATOR=="EOF", col row
tab MOTHER_Y_NO_FAT THRD_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
//
//TO GENERATE INDICATORS FOR REMEDIAL COURSEWORK
gen REMEDIAL_MATH=GRADE640041
replace REMEDIAL_MATH="1" if REMEDIAL_MATH=="PA"
replace REMEDIAL_MATH="1" if REMEDIAL_MATH=="S"
replace REMEDIAL_MATH="1" if REMEDIAL_MATH=="U"
replace REMEDIAL_MATH="1" if REMEDIAL_MATH=="W"
replace REMEDIAL_MATH="1" if REMEDIAL_MATH=="Z"
replace REMEDIAL_MATH="1" if GRADE640042=="S"
replace REMEDIAL_MATH="1" if GRADE640042=="U"
replace REMEDIAL_MATH="1" if GRADE640042=="W"
replace REMEDIAL_MATH="1" if GRADE640042=="Z"
replace REMEDIAL_MATH="0" if REMEDIAL_MATH==""
/*Need to Check if GRADE640043 is remedial or equivalent to 640ECM*/
gen REMEDIAL_ENG=GRADE350100
replace REMEDIAL_ENG="Y" if GRADE350100=="A"
replace REMEDIAL_ENG="Y" if GRADE350100=="B"
replace REMEDIAL_ENG="Y" if GRADE350100=="B+"
replace REMEDIAL_ENG="Y" if GRADE350100=="C"
replace REMEDIAL_ENG="Y" if GRADE350100=="C+"
replace REMEDIAL_ENG="Y" if GRADE350100=="D"
replace REMEDIAL_ENG="Y" if GRADE350100=="F"
replace REMEDIAL_ENG="Y" if GRADE350100=="W"
replace REMEDIAL_ENG="Y" if GRADE350100=="Z"

