*Final Dataset for Dissertation. Last Update 8.30.19
/*The purpose of this study is to determine if college retention rates (from first year to second year and from second year to third year)
differed among first generation Latino students in the Educational Opportunity Fund (EOF) program, 
and first generation Latino students who are not in the EOF program. In order to be in the EOF program, students must apply and be admitted
to the program based on academic and financial need. This study is done at Ruters, The State University of New Jersey's three campuses--
Rutgers University-New Brunswick, Rutgers University-Newark, and Rutgers University-Camden. The research question is: How does the
Educational Opportunity Fund program at Rutgers, The State University of New Jersey impact first generation latino student retention? The Hypothesis is
that Latino students in an EOF program retain at higher rates than those not in the program. I will be using regression discontinuity to identify whether the 
those in the program retain at higher rates than those who are not. Also considering propensity score matching*/

//If not using my personal computer use below
import excel "https://docs.google.com/uc?id=1xILLWJ5fy_8VxENiQK2yscbGBUFBlsY8&export=download", firstrow clear
//If using my personal computer use below
import excel "/Users/yosmerizroman/Downloads/Dissertation Dataset 8.19.19.xlsx", sheet("Dissertation Dataset 8.19.19") firstrow clear

*******DATA CLEANUP AND RECODES
destring *, replace
//TO GENERATE EOF INDICATORS
gen EOF_IND=.
replace EOF_IND=1 if EOF_CODES=="C"
replace EOF_IND=0 if inlist(EOF_CODES, "$" ,"G", "N",".", "P")
replace EOF_IND=0 if inlist(EOF_CODES, "R", "T", "U", "V", "W")
/*label EOF_IND==1 as "IN EOF" EOF_IND==0 as "No_EOF" */
//TO GENERATE INDICATORS FOR PARENT COMBINATIONS
recode FATHER_EDU (0 1 2=0 "Not_Attended") (3 4=1 "Attended"), gen(FATHER_COLLEGE)/*FATHER ATTENDED*/
recode MOTHER_EDU (0 1 2=0 "Not_Attended") (3 4=1 "Attended"), gen(MOTHER_COLLEGE)/*MOTHER ATTENDED*/
gen FM_COLLEGE=MOTHER_COLLEGE /*BOTH PARENTS ATTENDED*/
replace FM_COLLEGE="1" if FATHER_COLLEGE=="1" & MOTHER_COLLEGE=="1"
replace FM_COLLEGE="0" if FATHER_COLLEGE=="0" & MOTHER_COLLEGE=="0"
replace FM_COLLEGE="0" if FATHER_COLLEGE=="1" & MOTHER_COLLEGE=="0"
replace FM_COLLEGE="0" if FATHER_COLLEGE=="0" & MOTHER_COLLEGE=="1"
gen NEITHER_COLLEGE=FM_COLLEGE/*NEITHER PARENTS ATTENDED*/
replace NEITHER_COLLEGE="1" if FATHER_COLLEGE=="0" & MOTHER_COLLEGE=="0"
replace NEITHER_COLLEGE="0" if FATHER_COLLEGE=="1" & MOTHER_COLLEGE=="1"
replace NEITHER_COLLEGE="0" if FATHER_COLLEGE=="1" & MOTHER_COLLEGE=="0"
replace NEITHER_COLLEGE="0" if FATHER_COLLEGE=="0" & MOTHER_COLLEGE=="1"
gen FATHER_Y_NO_MOM=NEITHER_COLLEGE /*FATHER ATTENDED NOT MOTHER*/
replace FATHER_Y_NO_MOM="1" if FATHER_COLLEGE=="1" & MOTHER_COLLEGE=="0"
replace FATHER_Y_NO_MOM="0" if FATHER_COLLEGE=="1" & MOTHER_COLLEGE=="1"
replace FATHER_Y_NO_MOM="0" if FATHER_COLLEGE=="0" & MOTHER_COLLEGE=="0"
replace FATHER_Y_NO_MOM="0" if FATHER_COLLEGE=="0" & MOTHER_COLLEGE=="1"
gen MOTHER_Y_NO_FAT=FATHER_Y_NO_MOM /*MOTHER ATTENDED NOT FATHER*/
replace MOTHER_Y_NO_FAT="1" if FATHER_COLLEGE=="0" & MOTHER_COLLEGE=="1"
replace MOTHER_Y_NO_FAT="0" if FATHER_COLLEGE=="1" & MOTHER_COLLEGE=="1"
replace MOTHER_Y_NO_FAT="0" if FATHER_COLLEGE=="0" & MOTHER_COLLEGE=="0"
replace MOTHER_Y_NO_FAT="0" if FATHER_COLLEGE=="1" & MOTHER_COLLEGE=="0"
//TO GENERATE INDICATORS FOR REMEDIAL COURSEWORK
gen REMEDIAL_MATH=./*Student took remedial math */
replace REMEDIAL_MATH="1" if inlist (GRADE640041, "PA, "S", "U", "W", "Z")
replace REMEDIAL_MATH="1" if inlist (GRADE640042, "S", "U", "W", "Z")  
replace REMEDIAL_MATH="0" if REMEDIAL_MATH==""
gen REMEDIAL_ENG=GRADE350100/*Student took remedial English; Need to Check if GRADE640043 is remedial or equivalent to 640ECM*/
replace REMEDIAL_ENG="1" in inlist (GRADE350100, "A", "B", "B+", "C", "C+", "D", "F", "W", "Z"
replace REMEDIAL_ENG="0" if REMEDIAL_ENG==""
//TO GENERATE INDICATORS PREDICTIVE OF STUDENT RETENTION
replace DFG_SCHOOL="0" if DFG_SCHOOL==""
replace DFG_SCHOOL="1" if DFG_SCHOOL=="D"
/*Need to appropriately label below */
//label 1 "DFG_SCH" 0 "NO_DFG"
replace NAT_SCH_LUNCH="0" if inlist (NAT_SCH_LUNCH, "", "N")
replace NAT_SCH_LUNCH="1" if NAT_SCH_LUNCH=="Y"
replace EOF_SIBLING="Y" if EOF_SIBLING=="C"
replace EOF_SIBLING="1" if EOF_SIBLING=="Y"
replace EOF_SIBLING="0" if EOF_SIBLING=="N"
replace COLLEGE_PREP_PROG="0" if COLLEGE_PREP_PROG inlist (COLLEGE_PREP_PROG, "" "N")
replace COLLEGE_PREP_PROG="1" if COLLEGE_PREP_PROG inlist (COLLEGE_PREP_PROG, "C" "Y")
/*Need to appropriately label below */
label REGION_CD 1 "New Brunswick" 2 "Newark" 3 "Camden"
// TO CREATE LOCALS BASED ON CATEGORIES OF MEASURES PREDICTING RETENTION
local SCHOOLING HS_GPA HS_PCTILE_RANK ACT_COMP SATSCORE COLLEGE_PREP_PROG  /*Variables associated with student high school preparedness for college*/
local NEIGHBORHOOD DFG_SCHOOL HIGH_DITRESS_MNCPLTY /*Variables associated with neighborhood effects */
local INCOME HOUSEHOLDAGI EFC NAT_SCH_LUNCH /*Variables associated with Income */
local PAREDU FATHER_COLLEGE MOTHER_COLLEGE FM_COLLEGE FATHER_Y_NO_MOM MOTHER_Y_NO_FAT /*Parent Variables. First generation defined as neither parent completed a BA*/
local COLLEGE T1_GPA_TERM SP1_GPA_TERM SP1_GPA_CUM T2_GPA_TERM T2_GPA_CUM UNIT REGION_CD /*Variables Specific to grades while in college and Campus/School; for further research would be great to add other factors*/
local DEM GENDER AGE_AT_START /*Demographic Variables*/
local CATEGORICAL DFG_SCHOOL GENDER REGION_CD HIGH_DITRESS_MNCPLTY FATHER_COLLEGE MOTHER_COLLEGE FM_COLLEGE FATHER_Y_NO_MOM MOTHER_Y_NO_FAT NAT_SCH_LUNCH COLL_PREP_PROG EOF_SIBLING/*Categorical Variables*/
local CONTINUOUS HOUSEHOLDAGI EFC SATSCORE HS_GPA HS_PCTILE_RANK ACT_COMP AGE_AT_START T1_GPA_TERM SP1_GPA_TERM SP1_GPA_CUM T2_GPA_TERM T2_GPA_CUM /*Continuous Variables*/
local DEPENDENT /*Dependent Variables*/
////
//
///
//







//CATEGORICAL VARIABLES
tab DFG_SCHOOL, mi
tab EOF_IND DFG_SCHOOL, mi
tab EOF_IND, mi
tab EOF_IND GENDER, mi
tab EOF_IND REGION_CD, mi
tab EOF_IND HIGH_DITRESS_MNCPLTY, mi
tab FATHER_COLLEGE, mi
tab MOTHER_COLLEGE, mi
tab EOF_IND FATHER_COLLEGE, mi
tab EOF_IND MOTHER_COLLEGE, mi
tab EOF_IND NAT_SCH_LUNCH
tab EOF_IND EOF_SIBLING, mi
tab EOF_IND COLL_PREP_PROG, mi
tab EOF_IND REGION_CD 

//CONTINUOUS VARIABLES
misstable summarize
su HOUSEHOLDAGI if HOUSEHOLDAGI !=.
su HOUSEHOLDAGI if EOF_INDICATOR=="EOF"
su HOUSEHOLDAGI if EOF_INDICATOR=="NON-EOF"
su EFC if EFC !=.
su EFC if EOF_INDICATOR=="EOF"
su EFC if EOF_INDICATOR=="NON-EOF"
su SATSCORE if SATSCORE !=.
su SATSCORE if EOF_INDICATOR=="EOF"
su SATSCORE if EOF_INDICATOR=="NON-EOF"
su HS_GPA if HS_GPA !=.
su HS_GPA if EOF_INDICATOR=="EOF"
su HS_GPA if EOF_INDICATOR=="NON-EOF"
su HS_PCTILE_RANK if HS_PCTILE_RANK !=.
su HS_PCTILE_RANK if EOF_INDICATOR=="EOF"
su HS_PCTILE_RANK if EOF_INDICATOR=="NON-EOF"
su ACT_COMP if ACT_COMP !=.
su ACT_COMP if EOF_INDICATOR=="EOF"
su ACT_COMP if EOF_INDICATOR=="NON-EOF"
su AGE_AT_START if AGE_AT_START !=.
su AGE_AT_START if EOF_INDICATOR=="EOF"
su AGE_AT_START if EOF_INDICATOR=="NON-EOF"
su T1_GPA_TERM if T1_GPA_TERM !=.
su T1_GPA_TERM if EOF_INDICATOR=="EOF"
su T1_GPA_TERM if EOF_INDICATOR=="NON-EOF"
su SP1_GPA_TERM if SP1_GPA_TERM !=.
su SP1_GPA_TERM if EOF_INDICATOR=="EOF"
su SP1_GPA_TERM if EOF_INDICATOR=="NON-EOF"
su SP1_GPA_CUM if SP1_GPA_CUM !=.
su SP1_GPA_CUM if EOF_INDICATOR=="EOF"
su SP1_GPA_CUM if EOF_INDICATOR=="NON-EOF"
su T2_GPA_TERM if T2_GPA_TERM !=.
su T2_GPA_TERM if EOF_INDICATOR=="EOF"
su T2_GPA_TERM if EOF_INDICATOR=="NON-EOF"
su T2_GPA_CUM if T2_GPA_CUM !=.
su T2_GPA_CUM if EOF_INDICATOR=="EOF"
su T2_GPA_CUM if EOF_INDICATOR=="NON-EOF"
//DEPENDENT VARIABLES-RETENTION
tab SEC_FALL_RET if EOF_INDICATOR=="EOF"
tab SEC_FALL_RET if EOF_INDICATOR=="NON-EOF"
tab THRD_FALL_RET if EOF_INDICATOR=="EOF"
tab THRD_FALL_RET if EOF_INDICATOR=="NON-EOF"
//CROSSSTABULATIONS FY TO SO
tab GENDER SEC_FALL_RET, col row
tab GENDER SEC_FALL_RET if EOF_INDICATOR=="EOF", col row
tab GENDER SEC_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab UNIT SEC_FALL_RET, col row
tab UNIT SEC_FALL_RET if EOF_INDICATOR=="EOF", col row
tab UNIT SEC_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab REGION_CD SEC_FALL_RET, col row
tab REGION_CD SEC_FALL_RET if EOF_INDICATOR=="EOF", col row
tab REGION_CD SEC_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab DFG_SCHOOL SEC_FALL_RET, col row
tab DFG_SCHOOL SEC_FALL_RET if EOF_INDICATOR=="EOF", col row
tab DFG_SCHOOL SEC_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
/* POCKET OF POVERTY SAME AS HIGH DISTRESS MUNICIPALITY IN HOW ITS CODED*/
replace HIGH_DITRESS_MNCPLTY="HIGH DISTRESS MUNICIPALITY" if HIGH_DITRESS_MNCPLTY=="POCKET OF POVERTY"
tab HIGH_DITRESS_MNCPLTY
tab HIGH_DITRESS_MNCPLTY SEC_FALL_RET, col row
tab HIGH_DITRESS_MNCPLTY SEC_FALL_RET if EOF_INDICATOR=="EOF", col row
tab HIGH_DITRESS_MNCPLTY SEC_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab FATHER_COLLEGE SEC_FALL_RET, col row
tab FATHER_COLLEGE SEC_FALL_RET if EOF_INDICATOR=="EOF", col row
tab FATHER_COLLEGE SEC_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab MOTHER_COLLEGE SEC_FALL_RET, col row
tab MOTHER_COLLEGE SEC_FALL_RET if EOF_INDICATOR=="EOF", col row
tab MOTHER_COLLEGE SEC_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
//CROSSTABULATIONS FR TO SO
tab FATHER_MOTHER_ATTEND SEC_FALL_RET, col row
tab FATHER_MOTHER_ATTEND SEC_FALL_RET if EOF_INDICATOR=="EOF", col row
tab FATHER_MOTHER_ATTEND SEC_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab FATHER_MOTHER_NOT_ATTEND SEC_FALL_RET, col row
tab FATHER_MOTHER_NOT_ATTEND SEC_FALL_RET if EOF_INDICATOR=="EOF", col row
tab FATHER_MOTHER_NOT_ATTEND SEC_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab FATHER_Y_NO_MOM SEC_FALL_RET, col row
tab FATHER_Y_NO_MOM SEC_FALL_RET if EOF_INDICATOR=="EOF", col row
tab FATHER_Y_NO_MOM SEC_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab MOTHER_Y_NO_FAT SEC_FALL_RET, col row
tab MOTHER_Y_NO_FAT SEC_FALL_RET if EOF_INDICATOR=="EOF", col row
tab MOTHER_Y_NO_FAT SEC_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab EOF_SIBLING SEC_FALL_RET, col row
tab EOF_SIBLING SEC_FALL_RET if EOF_INDICATOR=="EOF", col row
tab EOF_SIBLING SEC_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab NAT_SCH_LUNCH SEC_FALL_RET, col row
tab NAT_SCH_LUNCH SEC_FALL_RET if EOF_INDICATOR=="EOF", col row
tab NAT_SCH_LUNCH SEC_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab COLL_PREP_PROG SEC_FALL_RET, col row
tab COLL_PREP_PROG SEC_FALL_RET if EOF_INDICATOR=="EOF", col row
tab COLL_PREP_PROG SEC_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
//CROSSSTABULATIONS SO TO JR
tab GENDER THRD_FALL_RET, col row
tab GENDER THRD_FALL_RET if EOF_INDICATOR=="EOF", col row
tab GENDER THRD_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab UNIT THRD_FALL_RET, col row
tab UNIT THRD_FALL_RET if EOF_INDICATOR=="EOF", col row
tab UNIT THRD_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab REGION_CD THRD_FALL_RET, col row
tab REGION_CD THRD_FALL_RET if EOF_INDICATOR=="EOF", col row
tab REGION_CD THRD_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab DFG_SCHOOL THRD_FALL_RET, col row
tab DFG_SCHOOL THRD_FALL_RET if EOF_INDICATOR=="EOF", col row
tab DFG_SCHOOL THRD_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab HIGH_DITRESS_MNCPLTY THRD_FALL_RET, col row
tab HIGH_DITRESS_MNCPLTY THRD_FALL_RET if EOF_INDICATOR=="EOF", col row
tab HIGH_DITRESS_MNCPLTY THRD_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab FATHER_COLLEGE THRD_FALL_RET, col row
tab FATHER_COLLEGE THRD_FALL_RET if EOF_INDICATOR=="EOF", col row
tab FATHER_COLLEGE THRD_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab MOTHER_COLLEGE THRD_FALL_RET, col row
tab MOTHER_COLLEGE THRD_FALL_RET if EOF_INDICATOR=="EOF", col row
tab MOTHER_COLLEGE THRD_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab EOF_SIBLING THRD_FALL_RET, col row
tab EOF_SIBLING THRD_FALL_RET if EOF_INDICATOR=="EOF", col row
tab EOF_SIBLING THRD_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab NAT_SCH_LUNCH THRD_FALL_RET, col row
tab NAT_SCH_LUNCH THRD_FALL_RET if EOF_INDICATOR=="EOF", col row
tab NAT_SCH_LUNCH THRD_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab COLL_PREP_PROG THRD_FALL_RET, col row
tab COLL_PREP_PROG THRD_FALL_RET if EOF_INDICATOR=="EOF", col row
tab COLL_PREP_PROG THRD_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
//
tab FATHER_MOTHER_ATTEND THRD_FALL_RET, col row
tab FATHER_MOTHER_ATTEND THRD_FALL_RET if EOF_INDICATOR=="EOF", col row
tab FATHER_MOTHER_ATTEND THRD_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab FATHER_MOTHER_NOT_ATTEND THRD_FALL_RET, col row
tab FATHER_MOTHER_NOT_ATTEND THRD_FALL_RET if EOF_INDICATOR=="EOF", col row
tab FATHER_MOTHER_NOT_ATTEND THRD_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab FATHER_Y_NO_MOM THRD_FALL_RET, col row
tab FATHER_Y_NO_MOM THRD_FALL_RET if EOF_INDICATOR=="EOF", col row
tab FATHER_Y_NO_MOM THRD_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
tab MOTHER_Y_NO_FAT THRD_FALL_RET, col row
tab MOTHER_Y_NO_FAT THRD_FALL_RET if EOF_INDICATOR=="EOF", col row
tab MOTHER_Y_NO_FAT THRD_FALL_RET if EOF_INDICATOR=="NON-EOF", col row
//
